LEARNING_RATE = 1e-3
BETA = 1.0
CLIP_NORM = 5.0
STEP_BETA = 0.0
MAXIMUM_BETA = 1.0
WARMUP = 1
KL_ANNEAL_ITER = 2
BATCH_SIZE = 64

NUM_EPOCHS = 100
LR_ANNEAL_RATE = 0.95
LR_ANNEAL_ITER = 5
TEST_ITERATION_FREQ = 1
PRINT_ITER_FREQ = 1
SAVE_ITER_FREQ = 1
